theme: jekyll-theme-minimal
title: Windows Terminal Dropdown
description: Automatically activate the built-in dropdown mode of Windows Terminal
logo: https://user-images.githubusercontent.com/50134239/131228634-f663d656-3826-4cd7-a440-b97ba729bc7b.png
show_downloads: true
github:
  script_url: https://github.com/cybardev/wt-dropdown/releases/download/v1.0/wt-dropdown.au3